### ISSUE TITLE
Compilation problem with gcc-11

### ISSUE THREAD

**Issue by ycollet** [brummer10/Mamba#38] opened 2021-03-29 19:13 UTC
Hello,
I am trying to compile mamba on fedora 34 beta with gcc-11 and I met the following error message:
```
/usr/include/smf.h:217:1: note: 'extern "C"' linkage started here
  217 | extern "C" {
      | ^~~~~~~~~~
In file included from /usr/include/glib-2.0/glib/gatomic.h:31,
                 from /usr/include/glib-2.0/glib/gthread.h:32,
                 from /usr/include/glib-2.0/glib/gasyncqueue.h:32,
                 from /usr/include/glib-2.0/glib.h:32,
                 from /usr/include/smf.h:221,
                 from Mamba.h:22,
                 from Mamba.cpp:22:
/usr/include/c++/11/type_traits:1250:3: error: template with C linkage
 1250 |   template<typename _Tp>
      |   ^~~~~~~~
In file included from Mamba.h:22,
                 from Mamba.cpp:22:
```

**Comment by brummer10** [comment] 2021-03-29 19:18
that looks pretty much like a problem in libsmf. I'll look into it, thanks for reporting.
regards
hermann

**Comment by ycollet** [comment] 2021-03-29 19:19
I agreed. I tried to include smf.h in extern "C" in mamba.h and it doesn't fix anything.
Looking into smf.h ....

**Comment by brummer10** [comment] 2021-03-29 19:27
I don't know exactly, but usually you included other headers outside the extern "C" macro, in smf.h I see that stdio.h and glib.h been included inside the macro. That may be a problem with gcc 11 but I don't know.

**Comment by ycollet** [comment] 2021-03-29 19:29
I met the same kind of problem with gxtuner.
gcc 11 enable c++17 by default. Maybe the problem comes from here ...

**Comment by brummer10** [comment] 2021-03-29 19:37
Ah, maybe it helps to add -std=c++11 to the CXXFLAGS in the makefile?

**Comment by ycollet** [comment] 2021-03-29 19:48
No, not yet.
I set CXXFLAGS=-std=C++11 and I realized that the Makefile managed CPPFLAGS instead of CXXFLAGS.
So, I tried to add -std=c++11 to CPPFLAGS. But still the same problem.
I am looking for a solution ...

**Comment by ycollet** [comment] 2021-03-29 20:41
I tried the -fno-new-ttp-matching flags from the changeog https://gcc.gnu.org/gcc-11/changes.html
But It doesn"t works.

**Comment by ycollet** [comment] 2021-03-29 20:45
Finally, this combination has worked for gxtuner:
export CPPFLAGS="-D__cplusplus -std=c++11 $CXXFLAGS"

**Comment by ycollet** [comment] 2021-03-29 20:54
Doesn't work for Mamba.
I stop for the night ...

**Comment by brummer10** [comment] 2021-03-30 03:50
The Mamba makefile use CXXFLAGS
I've added the -std=gnu++14 flag now, hope that helps.

**Comment by brummer10** [comment] 2021-03-30 06:30
I do some tests with -std=gnu++17, found some issues in the Mamba source which I've solved now. 
But the issue with libsmf I can't reproduce here when build with gnu++17 enabled. 
True, I'm still on the gcc version 10.2.1

**Comment by brummer10** [comment] 2021-03-30 08:16
So I do some research on this issue, and it seems that indeed the issue is that smf.h include glib.h in a extern "C" block.
That is still no problem here on debian/sid with gcc 10.2, but maybe gcc-11 is a bit more strict about that.
I found a possible workaround for that, by including type_traits in a external C++ block before include smf.h
Still I didn't realy know if that works or not, as we don't have gcc-11 on debian jet. 
You may try it your self before I push such a change to the repository. 
Just open the file mamba.h and insert the following block
```

extern "C++" {
#include <type_traits>
}
```


 just above the line 
`#include <smf.h>`

let me know if that helps, if so I'll add it to the repository.
regards
hermann

**Comment by ycollet** [comment] 2021-03-30 08:31
Thanks a lot, I will try ASAP.

**Comment by ycollet** [comment] 2021-03-30 20:56
Works here. Thanks for this fix.

**Comment by brummer10** [comment] 2021-03-31 04:13
Okay, nice, So I've pushed it to the repository now. 
Closed this issue.

**Closed by brummer10** 2021-03-31 04:13 UTC
